#include <gst/gst.h>
#include "custom_meta.h"


typedef struct _GstPluginA GstPluginA;

typedef struct {
    guint64 frame_counter;
} GstPluginAPrivate;

G_DECLARE_FINAL_TYPE(GstPluginA, gst_plugin_a, GST, PLUGIN_A, GstElement)

struct _GstPluginA {
    GstElement parent;
    
    /* Pads */
    GstPad *sinkpad;
    GstPad *srcpad;
};

G_DEFINE_TYPE_WITH_PRIVATE(GstPluginA, gst_plugin_a, GST_TYPE_ELEMENT)

#define GST_TYPE_PLUGIN_A (gst_plugin_a_get_type())

//==============================================================
// Инициализация класса элемента
//==============================================================
static void gst_plugin_a_class_init(GstPluginAClass *klass) {
  GstElementClass *element_class = GST_ELEMENT_CLASS(klass);
  
  // Настройка метаданных плагина
  gst_element_class_set_static_metadata(
    element_class,
    "Plugin A - Добавляет метаданные",
    "Filter/Metadata",
    "Добавляет пользовательские метаданные к буферам",
    "Ваше Имя <test@example.com>"
  );

  // Регистрация pad
  gst_element_class_add_pad_template(
    element_class,
    gst_pad_template_new(
      "sink",
      GST_PAD_SINK,
      GST_PAD_ALWAYS,
      GST_CAPS_ANY // Принимаем любые типы данных
    )
  );

  gst_element_class_add_pad_template(
    element_class,
    gst_pad_template_new(
      "src",
      GST_PAD_SRC,
      GST_PAD_ALWAYS,
      GST_CAPS_ANY // Отправляем те же типы данных
    )
  );
}


//==============================================================
// Обработка данных
//==============================================================
static GstFlowReturn gst_plugin_a_chain(
    GstPad *pad, 
    GstObject *parent, 
    GstBuffer *buffer
) {

    GstPluginA *plugin = GST_PLUGIN_A(parent);
    GstPluginAPrivate *priv = gst_plugin_a_get_instance_private(plugin);
    // Добавляем метаданные к буферу   
    MyCustomMeta *meta = (MyCustomMeta *)gst_buffer_add_meta(
        buffer,
        MY_CUSTOM_META_INFO,
        NULL  
    );

    if (meta) {
        meta->frame_id = priv->frame_counter++;
        meta->custom_data = g_strdup("Generated by PluginA");
    }

    if (!meta) {
        GST_ERROR("Не удалось добавить метаданные!");
        return GST_FLOW_ERROR;
    }

  // Передаём буфер дальше по pipeline
  return gst_pad_push(plugin->srcpad, buffer);
}

//==============================================================
// Инициализация экземпляра элемента
//==============================================================
static void gst_plugin_a_init(GstPluginA *plugin) {
  // Инициализация приватных данных
  GstPluginAPrivate *priv = gst_plugin_a_get_instance_private(plugin);
  priv->frame_counter = 0;

  // Создаём pad'ы
    plugin->sinkpad = gst_pad_new_from_template(
        gst_element_class_get_pad_template(GST_ELEMENT_GET_CLASS(plugin), "sink"), // <- Добавлена закрывающая скобка
        "sink" 
    );
  plugin->srcpad = gst_pad_new_from_template(
    gst_element_class_get_pad_template(GST_ELEMENT_GET_CLASS(plugin), "src"),
    "src"
    );

  // Устанавливаем функции обработки данных
  gst_pad_set_chain_function(plugin->sinkpad, gst_plugin_a_chain);

  // Добавляем pad'ы к элементу
  gst_element_add_pad(GST_ELEMENT(plugin), plugin->sinkpad);
  gst_element_add_pad(GST_ELEMENT(plugin), plugin->srcpad);
}


//==============================================================
// Регистрация плагина
//==============================================================
static gboolean plugin_init(GstPlugin *plugin) {
  return gst_element_register(
    plugin,
    "plugina",
    GST_RANK_NONE,
    GST_TYPE_PLUGIN_A
  );
}

// Определение информации о плагине
GST_PLUGIN_DEFINE(
  GST_VERSION_MAJOR,
  GST_VERSION_MINOR,
  plugina,
  "Пользовательский плагин A",
  plugin_init,
  VERSION,
  "LGPL",
  "gst-meta-plugin-example",
  "https://example.com"
)